apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tigerd.fullname" . }}
  labels:
    {{- include "tigerd.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: 4904
    external_url: {{ .Values.tigerd.external_url }}
    log_level: {{ .Values.tigerd.log_level | default "INFO" }}
    log_json: true
