apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tigerd.fullname" . }}
  labels:
    {{- include "tigerd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deploy.replica }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tigerd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deploy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tigerd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tigerd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deploy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deploy.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tigerd", "server", "--config", "/etc/absurdlab/tigerd/config.yaml"]
          env:
            - name: TIGERD_SERVER_JWKS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tigerd.server_jwks_secret.name }}
                  key: {{ .Values.tigerd.server_jwks_secret.key }}
          ports:
            - name: http
              containerPort: 4904
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /etc/absurdlab/tigerd
              name: tigerd
              readOnly: true
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
      volumes:
        - name: tigerd
          projected:
            sources:
              - configMap:
                  name: {{ include "tigerd.fullname" . }}
                  items:
                    - key: config.yaml
                      path: config.yaml
      {{- with .Values.deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
