apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigerd.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
  labels:
    {{- include "tigerd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tigerd.selectorLabels" . | nindent 4 }}
