name: Release charts

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: setup helm
        uses: azure/setup-helm@v3
      - name: lint charts
        run: |
          helm lint ./charts/tigerd
      - name: release charts
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.PAT_TOKEN }}"